'use client';

import { useEffect, useState } from 'react';
import BookLoader from '@/components/book-loader';

// Shown while a custom game is being generated by the LLM. Gives a friendly time
// estimate and a progress bar that eases toward ~92% across the expected window
// (it never finishes on its own — the generated content arriving unmounts this),
// so the wait feels bounded instead of open-ended.
export default function GameGenLoading({ label = 'Building your game…', estimateSeconds = 18 }) {
  const [pct, setPct] = useState(6);

  useEffect(() => {
    const start = Date.now();
    const id = setInterval(() => {
      const elapsed = (Date.now() - start) / 1000;
      setPct(Math.min(92, 6 + (elapsed / estimateSeconds) * 86));
    }, 200);
    return () => clearInterval(id);
  }, [estimateSeconds]);

  const low = Math.max(5, Math.round(estimateSeconds * 0.75));
  const high = Math.round(estimateSeconds * 1.4);

  return (
    <div className="max-w-md mx-auto py-16 text-center">
      <BookLoader message={label} size="lg" />
      <p className="mt-6 text-sm" style={{ color: 'var(--ink-dim, #64748b)' }}>
        This usually takes about <span className="font-semibold">{low}–{high} seconds</span>.
      </p>
      <div className="mt-4 h-1.5 rounded-full overflow-hidden mx-auto max-w-xs" style={{ background: 'var(--line, rgba(10,36,67,.1))' }}>
        <div
          className="h-full rounded-full transition-[width] duration-200 ease-out"
          style={{ width: `${pct}%`, background: 'linear-gradient(90deg, var(--accent, #0055FF), var(--accent2, #3B94FF))' }}
        />
      </div>
    </div>
  );
}
