'use client';

import BookLoader from '@/components/book-loader';
import GenProgressBar from '@/components/gen-progress-bar';

// Shown while a custom game is being generated by the LLM. Gives a friendly time
// estimate and a progress bar (see GenProgressBar) so the wait feels bounded
// instead of open-ended.
export default function GameGenLoading({ label = 'Building your game…', estimateSeconds = 18 }) {
  const low = Math.max(5, Math.round(estimateSeconds * 0.75));
  const high = Math.round(estimateSeconds * 1.4);

  return (
    <div className="max-w-md mx-auto py-16 text-center">
      <BookLoader message={label} size="lg" />
      <p className="mt-6 text-sm" style={{ color: 'var(--ink-dim, #64748b)' }}>
        This usually takes about <span className="font-semibold">{low}–{high} seconds</span>.
      </p>
      <GenProgressBar estimateSeconds={estimateSeconds} className="mt-4" />
    </div>
  );
}
