const DEMO_LEARNER = null;
const DEMO_LESSON_HISTORY = [];
const DEMO_GOALS = [];
const DEMO_PROJECTS = [];
const DEMO_SKILL_EVALUATIONS = [];
const DEMO_XP_EVENTS = [];
const DEMO_BADGES_EARNED = [];
const DEMO_QUIZ_CARDS = [];
const DEMO_KNOWLEDGE = [];

export {
  DEMO_LEARNER,
  DEMO_LESSON_HISTORY,
  DEMO_GOALS,
  DEMO_PROJECTS,
  DEMO_SKILL_EVALUATIONS,
  DEMO_XP_EVENTS,
  DEMO_BADGES_EARNED,
  DEMO_QUIZ_CARDS,
  DEMO_KNOWLEDGE,
};
