export const QUESTS = [
  {
    id: 'prompt-library',
    title: 'Build Your Personal Prompt Library',
    description: 'Create a reusable collection of prompts tailored to your daily tasks. Walk away with a document you can reference every day.',
    duration: '20-30 min',
    difficulty: 'Beginner',
    difficultyColor: 'bg-green-100 text-green-700',
    icon: '📚',
    xpReward: 100,
    steps: [
      {
        id: 'identify-tasks',
        title: 'Identify Your Top 5 Repetitive Tasks',
        description: 'Think about your typical work week. What tasks do you do repeatedly that involve writing, analyzing, or communicating?',
        task: 'Write down 5 tasks you do at least weekly that could benefit from AI assistance. Examples: drafting emails, summarizing meetings, creating reports.',
        successCriteria: 'You have a list of 5 specific, recurring tasks from your actual work.',
        tips: [
          'Think about what takes the most time',
          'Focus on tasks that involve text — writing, reading, or organizing information',
          'Be specific: "write customer onboarding emails" is better than "write stuff"',
        ],
      },
      {
        id: 'write-first-prompt',
        title: 'Write Your First Reusable Prompt',
        description: 'Take the #1 task from your list and craft a prompt using the RCTF framework: Role, Context, Task, Format.',
        task: 'Write a prompt for your most frequent task. Include: who the AI should act as (Role), background info (Context), what to do (Task), and how to structure the output (Format).',
        successCriteria: 'You have a complete RCTF prompt that you can try in AI Chat and get useful output.',
        tips: [
          'Start with "You are a [role] who..."',
          'Include specific details about your company/team',
          'Specify the exact output format you want',
        ],
      },
      {
        id: 'test-and-refine',
        title: 'Test and Refine Your Prompt',
        description: 'Try your prompt in the Chat and iterate on it. Most prompts need 2-3 rounds of tweaking before they\'re reliable.',
        task: 'Paste your prompt into AI Chat, evaluate the output, and refine it. Try it at least 3 times with different inputs to make sure it works consistently.',
        successCriteria: 'Your prompt produces consistently useful output across multiple test runs.',
        tips: [
          'If output is too long, add "Keep it under X sentences"',
          'If output is too generic, add more context about your specific situation',
          'Save the final version — this is your template',
        ],
      },
      {
        id: 'build-full-library',
        title: 'Complete Your Prompt Library',
        description: 'Repeat the process for your remaining tasks. You now have a personal prompt library you can use daily.',
        task: 'Write RCTF prompts for your remaining 4 tasks. Test each one at least once. Save all 5 in a document or note you can access easily.',
        successCriteria: 'You have 5 tested, reusable prompts saved in an accessible location.',
        tips: [
          'Keep all prompts in one document for easy access',
          'Add notes about when to use each one',
          'Share with teammates who do similar work',
        ],
      },
    ],
  },
  {
    id: 'email-workflow',
    title: 'Automate Your Email Workflow',
    description: 'Design and test an AI-powered email response system for your most common customer inquiries.',
    duration: '30-45 min',
    difficulty: 'Intermediate',
    difficultyColor: 'bg-yellow-100 text-yellow-700',
    icon: '📧',
    xpReward: 150,
    steps: [
      {
        id: 'audit-emails',
        title: 'Audit Your Email Patterns',
        description: 'Look through your sent folder from the past week. Identify the types of emails you write most often.',
        task: 'Categorize your recent sent emails into 3-5 types (e.g., "scheduling follow-up", "feature question response", "status update"). Note which type you send most.',
        successCriteria: 'You have 3-5 email categories with your top category identified.',
        tips: ['Check your sent folder for the last 7 days', 'Group similar emails together', 'Count how many of each type you sent'],
      },
      {
        id: 'create-template-prompt',
        title: 'Create an Email Template Prompt',
        description: 'Build a detailed prompt that can generate your most common email type with just a few inputs from you.',
        task: 'Write a prompt that takes key variables (recipient name, situation, desired outcome) and generates a complete email in your tone and style. Include an example of a good email you\'ve written as a reference.',
        successCriteria: 'Your prompt generates emails that sound like you wrote them.',
        tips: ['Include 1-2 real examples of emails you\'ve written', 'Specify your tone (warm, professional, casual)', 'Add constraints like max length and must-include elements'],
      },
      {
        id: 'build-variations',
        title: 'Build Response Variations',
        description: 'Create prompt variations for positive, neutral, and difficult scenarios within your email category.',
        task: 'Adapt your template prompt for 3 scenarios: a positive/easy response, a neutral/standard response, and a difficult/sensitive response. Test each one.',
        successCriteria: 'You have 3 tested prompt variations that handle different situations appropriately.',
        tips: ['The difficult scenario needs the most careful prompting', 'Add tone guidance: "empathetic but firm" for difficult cases', 'Test with real scenarios from your past week'],
      },
      {
        id: 'speed-test',
        title: 'Speed Test Your Workflow',
        description: 'Time yourself using AI vs. writing from scratch to see how much time you actually save.',
        task: 'Write one email from scratch (time it). Then use your AI prompt for a similar email (time it). Calculate your time savings.',
        successCriteria: 'You have concrete time-savings data for your email workflow.',
        tips: ['Be honest about the timing — include review/edit time for AI output', 'Quality should be equal or better, not just faster', 'Even 30% time savings adds up over hundreds of emails'],
      },
      {
        id: 'document-workflow',
        title: 'Document Your Email Workflow',
        description: 'Save your email prompts and workflow so you and your team can use them consistently.',
        task: 'Create a short document with: your email categories, the prompt for each, example inputs, and your measured time savings. Share it with one teammate.',
        successCriteria: 'Your workflow is documented and shared with at least one other person.',
        tips: ['Include "how to customize" notes for teammates', 'Add your time-savings data — it motivates adoption', 'Keep it simple — one page max'],
      },
    ],
  },
  {
    id: 'meeting-assistant',
    title: 'Create a Meeting Assistant',
    description: 'Build a complete meeting workflow: agenda generation, note-taking prompts, and automated follow-up emails.',
    duration: '45-60 min',
    difficulty: 'Intermediate',
    difficultyColor: 'bg-yellow-100 text-yellow-700',
    icon: '🤝',
    xpReward: 200,
    steps: [
      {
        id: 'pre-meeting',
        title: 'Build a Pre-Meeting Agenda Generator',
        description: 'Create a prompt that generates structured meeting agendas from a brief description of the meeting purpose.',
        task: 'Write a prompt that takes a meeting topic, attendees, and duration, then outputs a structured agenda with time allocations, discussion questions, and pre-read items.',
        successCriteria: 'Your prompt generates useful, realistic agendas you\'d actually send to attendees.',
        tips: ['Include standard sections: objectives, discussion items, action review, next steps', 'Add time allocations that respect the meeting duration', 'Generate 2-3 discussion questions per agenda item'],
      },
      {
        id: 'note-structure',
        title: 'Design a Note-Taking Template',
        description: 'Create a structured note-taking format that makes it easy to capture key information during meetings.',
        task: 'Build a prompt that takes raw, messy meeting notes and transforms them into a clean format with: decisions made, action items (with owners), open questions, and key takeaways.',
        successCriteria: 'The template clearly separates decisions, actions, and open items from your raw notes.',
        tips: ['Test with intentionally messy notes', 'Action items should always have an owner and deadline', 'Keep the output scannable — bullet points, not paragraphs'],
      },
      {
        id: 'action-extraction',
        title: 'Automate Action Item Extraction',
        description: 'Refine your note-taking prompt to reliably extract action items with owners and deadlines.',
        task: 'Take notes from a recent real meeting and run them through your prompt. Verify that every action item is captured with the correct owner. Iterate until extraction is reliable.',
        successCriteria: 'Your prompt catches all action items and correctly assigns owners from the notes.',
        tips: ['Common failures: missing implied action items, wrong owner attribution', 'Add instructions to flag items with unclear owners', 'Test with 2-3 different meetings\' notes'],
      },
      {
        id: 'follow-up-email',
        title: 'Generate Follow-Up Emails',
        description: 'Build a prompt that turns your structured meeting notes into a professional follow-up email.',
        task: 'Create a prompt that takes your cleaned-up meeting notes and generates a follow-up email with: summary, action items, deadlines, and next meeting date.',
        successCriteria: 'The follow-up email is ready to send with minimal editing.',
        tips: ['Keep follow-up emails brief — people skim', 'Bold the action items so they stand out', 'Include a "reply by" date for any items that need confirmation'],
      },
      {
        id: 'end-to-end',
        title: 'Run the Full Workflow End-to-End',
        description: 'Test your complete meeting assistant workflow from agenda to follow-up on a real upcoming meeting.',
        task: 'For your next meeting: (1) generate the agenda, (2) use the note template during the meeting, (3) clean up notes with AI, (4) generate and send the follow-up email.',
        successCriteria: 'You\'ve used the full workflow for a real meeting and identified what to improve.',
        tips: ['The first run always reveals gaps', 'Note which step saves the most time', 'Refine the weakest prompt after your first run'],
      },
      {
        id: 'share-workflow',
        title: 'Package and Share Your Meeting Assistant',
        description: 'Document the complete workflow so others on your team can use it too.',
        task: 'Create a one-page guide with all four prompts, usage instructions, and your time-savings estimate. Share it with your team or manager.',
        successCriteria: 'Your meeting assistant workflow is documented and shared.',
        tips: ['Include before/after examples', 'Estimate total time saved per meeting', 'Offer to walk a teammate through it'],
      },
    ],
  },
  {
    id: 'rctf-framework',
    title: 'Master the RCTF Framework',
    description: 'Learn the Role-Context-Task-Format framework that makes every prompt more effective. Practice with real examples from your work.',
    duration: '15-20 min',
    difficulty: 'Beginner',
    difficultyColor: 'bg-green-100 text-green-700',
    icon: '🎯',
    xpReward: 75,
    steps: [
      {
        id: 'learn-rctf',
        title: 'Understand the Four Components',
        description: 'RCTF stands for Role, Context, Task, and Format. Each component gives the AI critical information to produce useful output.',
        task: 'Learn each component:\n\n• Role: Who should the AI act as? ("You are a senior customer success manager")\n• Context: What background is needed? ("The customer has been with us for 6 months")\n• Task: What specifically should the AI do? ("Write a renewal check-in email")\n• Format: How should output be structured? ("Under 150 words, warm professional tone")',
        successCriteria: 'You can name all four RCTF components and explain what each one does.',
        tips: ['Role sets the AI\'s expertise level and perspective', 'Context prevents generic responses', 'Task should be specific and actionable', 'Format controls length, tone, and structure'],
      },
      {
        id: 'compare-prompts',
        title: 'See the Difference RCTF Makes',
        description: 'Compare a vague prompt vs. an RCTF prompt to see the quality difference firsthand.',
        task: 'Try both in Chat:\n\nVague: "Write an email to a customer"\n\nRCTF: "You are a customer success manager at a home services software company (Role). A long-time customer hasn\'t logged in for 2 weeks (Context). Write a friendly check-in email that offers help and highlights a new feature (Task). Under 100 words, warm tone, include a call-to-action (Format)."\n\nCompare the outputs.',
        successCriteria: 'You can clearly see how RCTF produces more relevant, usable output.',
        tips: ['The vague prompt will produce something generic', 'The RCTF prompt should produce something you\'d actually send', 'Notice how much less editing the RCTF version needs'],
      },
      {
        id: 'write-own-rctf',
        title: 'Write Your Own RCTF Prompt',
        description: 'Apply the framework to a real task from your job.',
        task: 'Pick a task you did this week. Write an RCTF prompt for it, labeling each section. Test it in Chat and refine until the output is genuinely useful.',
        successCriteria: 'You have a working RCTF prompt for a real task that produces quality output.',
        tips: ['Label each section: [Role] [Context] [Task] [Format]', 'The more specific your Context, the better the output', 'If output isn\'t great, the fix is usually in Context or Format'],
      },
      {
        id: 'teach-it',
        title: 'Explain RCTF to a Colleague',
        description: 'The best way to cement knowledge is to teach it. Share what you learned.',
        task: 'Explain the RCTF framework to a colleague (in person, Slack, or email). Share your before/after prompt comparison and your custom RCTF prompt as examples.',
        successCriteria: 'You\'ve explained RCTF to at least one person and shared an example.',
        tips: ['Keep it simple — the framework is intuitive once you see an example', 'Lead with the before/after comparison', 'Offer to help them write their first RCTF prompt'],
      },
    ],
  },
  {
    id: 'customer-faq',
    title: 'Build a Customer FAQ Bot',
    description: 'Create a set of AI-powered responses for your team\'s most frequently asked customer questions.',
    duration: '30-40 min',
    difficulty: 'Intermediate',
    difficultyColor: 'bg-yellow-100 text-yellow-700',
    icon: '💬',
    xpReward: 150,
    steps: [
      {
        id: 'collect-faqs',
        title: 'Collect Your Top 10 FAQs',
        description: 'Gather the questions your team gets asked most often by customers.',
        task: 'Review your recent support tickets, emails, or chat logs. List the 10 most common questions customers ask. Include the exact wording they use.',
        successCriteria: 'You have 10 real customer questions ranked by frequency.',
        tips: ['Check your ticket system for common categories', 'Ask teammates what questions they answer most', 'Use actual customer wording, not internal terminology'],
      },
      {
        id: 'craft-responses',
        title: 'Craft AI-Powered Responses',
        description: 'Build prompts that generate accurate, on-brand responses to each FAQ.',
        task: 'For your top 3 FAQs, write a prompt that generates a response matching your team\'s tone and accuracy standards. Include key details the response must contain.',
        successCriteria: 'Your top 3 FAQ responses are accurate, on-brand, and ready to send with minimal editing.',
        tips: ['Include company-specific details (product names, feature names)', 'Add tone guidelines matching your team\'s style', 'Include a "must mention" list for each FAQ'],
      },
      {
        id: 'add-personalization',
        title: 'Add Personalization Variables',
        description: 'Make your responses adaptable to different customer situations.',
        task: 'Update your FAQ prompts to accept variables like customer name, account type, and specific situation. Test with 3 different customer scenarios.',
        successCriteria: 'Your prompts produce personalized responses that feel individual, not templated.',
        tips: ['Common variables: customer name, plan type, tenure', 'Test with a brand-new customer AND a long-time customer', 'The response should feel personal, not like a mail merge'],
      },
      {
        id: 'complete-library',
        title: 'Complete All 10 FAQ Responses',
        description: 'Finish building prompts for all 10 of your FAQs.',
        task: 'Write and test prompts for your remaining 7 FAQs. Organize them in a document your team can reference.',
        successCriteria: 'All 10 FAQ prompts are tested and saved in an accessible document.',
        tips: ['Organize by category (billing, features, troubleshooting)', 'Include "when to use" notes for each', 'Flag any FAQs that need a human touch'],
      },
      {
        id: 'team-rollout',
        title: 'Share With Your Team',
        description: 'Roll out your FAQ bot to teammates and gather feedback.',
        task: 'Share your FAQ prompt library with your team. Have at least 2 people try it for real customer interactions. Collect feedback and iterate.',
        successCriteria: 'At least 2 teammates have used your FAQ prompts and you\'ve incorporated their feedback.',
        tips: ['Start with willing early adopters', 'Ask specifically what didn\'t work', 'Update prompts based on real-world usage'],
      },
    ],
  },
  {
    id: 'data-analysis',
    title: 'Analyze Data with AI',
    description: 'Learn to use AI for data analysis: spotting trends, summarizing datasets, and generating insights from numbers.',
    duration: '30-45 min',
    difficulty: 'Intermediate',
    difficultyColor: 'bg-yellow-100 text-yellow-700',
    icon: '📊',
    xpReward: 150,
    steps: [
      {
        id: 'structure-data',
        title: 'Learn to Structure Data for AI',
        description: 'AI works best with clearly structured data. Learn the formats that get the best results.',
        task: 'Take a small dataset from your work (10-20 rows). Format it as a clean table or CSV. Try pasting it into Chat with "Summarize the key trends in this data." Compare results with messy vs. clean formatting.',
        successCriteria: 'You understand how data formatting affects AI output quality.',
        tips: ['CSV or markdown tables work best', 'Include column headers', 'Remove sensitive data before pasting'],
      },
      {
        id: 'trend-analysis',
        title: 'Spot Trends and Patterns',
        description: 'Use AI to identify trends you might miss when looking at data manually.',
        task: 'Give AI a dataset and ask it to: (1) identify the top 3 trends, (2) flag any anomalies, (3) compare this period to the previous period. Evaluate whether the insights are accurate.',
        successCriteria: 'AI identified at least one useful trend or anomaly you hadn\'t noticed.',
        tips: ['Always verify AI claims against actual data', 'Ask for specific numbers, not vague observations', 'AI is great at pattern-matching but can hallucinate statistics'],
      },
      {
        id: 'summary-report',
        title: 'Generate an Insights Summary',
        description: 'Build a prompt that turns raw data into a stakeholder-ready summary.',
        task: 'Create a prompt that takes your data and generates a brief report with: key findings, trends, recommendations, and next steps. Format it for a specific audience (manager, team, or executives).',
        successCriteria: 'The generated report is clear, accurate, and appropriate for your target audience.',
        tips: ['Specify the audience — executive summaries differ from team updates', 'Each finding should have a "so what" implication', 'Ask AI to caveat conclusions it\'s less confident about'],
      },
      {
        id: 'comparison-analysis',
        title: 'Build a Comparison Analysis Prompt',
        description: 'Create a reusable prompt for comparing two time periods, segments, or categories.',
        task: 'Write a prompt that compares two data segments and highlights: what improved, what declined, biggest changes, and recommended actions. Test with real data.',
        successCriteria: 'Your comparison prompt produces actionable insights for a real report.',
        tips: ['Comparisons are one of AI\'s strongest data tasks', 'Ask for percentage changes, not just directional indicators', 'Include context about what "good" looks like for your metrics'],
      },
      {
        id: 'automate-reporting',
        title: 'Create a Repeatable Reporting Workflow',
        description: 'Package your data analysis prompts into a workflow you can run weekly or monthly.',
        task: 'Document your workflow: (1) how to prepare data, (2) which prompts to run, (3) how to verify output, (4) how to format the final report. Run it end-to-end once.',
        successCriteria: 'You have a documented, repeatable data analysis workflow.',
        tips: ['The goal is consistency — same quality every time', 'Include a verification checklist for catching AI errors', 'Estimate time saved per reporting cycle'],
      },
    ],
  },
  {
    id: 'first-workflow',
    title: 'Create Your First AI Workflow',
    description: 'Chain multiple AI prompts together to automate a complete work task from start to finish.',
    duration: '15-20 min',
    difficulty: 'Beginner',
    difficultyColor: 'bg-green-100 text-green-700',
    icon: '⚡',
    xpReward: 75,
    steps: [
      {
        id: 'pick-task',
        title: 'Pick a Multi-Step Task',
        description: 'Identify a task that has multiple steps which could each benefit from AI help.',
        task: 'Think of a task you do that involves 2-3 steps. Example: (1) read customer feedback, (2) identify themes, (3) write a summary. Write down each step.',
        successCriteria: 'You have a 2-3 step task broken down into individual steps.',
        tips: ['Good candidates: anything where output from step 1 becomes input for step 2', 'Keep it simple — 2-3 steps is plenty', 'Common patterns: gather → analyze → write'],
      },
      {
        id: 'chain-prompts',
        title: 'Chain Your Prompts Together',
        description: 'Write a prompt for each step, where the output of one feeds into the next.',
        task: 'Write prompts for each step of your task. Run step 1, take its output, and use it as input for step 2. Continue through all steps.',
        successCriteria: 'You\'ve successfully chained 2-3 prompts to complete the full task.',
        tips: ['Write prompts that produce clean output for the next step', 'If output from step 1 is messy, add format instructions', 'You can ask AI to format output specifically for the next prompt'],
      },
      {
        id: 'save-workflow',
        title: 'Save Your Workflow',
        description: 'Document your multi-step workflow so you can repeat it quickly.',
        task: 'Write down: (1) each step\'s prompt, (2) what to copy between steps, (3) estimated time savings. Run it one more time to confirm it works.',
        successCriteria: 'Your workflow is documented and verified.',
        tips: ['Name your workflow something memorable', 'Note any steps that need human judgment', 'This is the building block for more complex automations'],
      },
    ],
  },
  {
    id: 'advanced-prompting',
    title: 'Advanced Prompt Engineering',
    description: 'Level up with advanced techniques: chain-of-thought, few-shot examples, and systematic prompt testing.',
    duration: '40-50 min',
    difficulty: 'Advanced',
    difficultyColor: 'bg-red-100 text-red-700',
    icon: '🧠',
    xpReward: 250,
    steps: [
      {
        id: 'chain-of-thought',
        title: 'Master Chain-of-Thought Prompting',
        description: 'Learn to make AI "show its work" for better reasoning and more accurate outputs.',
        task: 'Take a complex question from your work. First, ask it directly. Then ask again with "Think through this step by step. Show your reasoning before your final answer." Compare quality.',
        successCriteria: 'You can see how chain-of-thought produces more thorough, accurate responses.',
        tips: ['Most valuable for complex, multi-factor decisions', 'Trigger phrases: "step by step", "think through", "reason about"', 'You can also provide the structure: "First consider X, then Y, then Z"'],
      },
      {
        id: 'few-shot',
        title: 'Use Few-Shot Examples',
        description: 'Provide examples of desired input/output pairs to dramatically improve consistency.',
        task: 'Write a prompt with 2-3 examples of the exact input→output pattern you want. Give it a new input and check if the output matches. Compare to the same prompt without examples.',
        successCriteria: 'Few-shot examples produce noticeably more consistent output.',
        tips: ['2-3 examples is usually enough', 'Cover different scenarios (easy, medium, edge case)', 'Powerful for formatting, tone, and classification tasks'],
      },
      {
        id: 'negative-prompting',
        title: 'Use Constraints and Negative Prompting',
        description: 'Sometimes telling AI what NOT to do is as important as telling it what to do.',
        task: 'Take a prompt where the output is "almost right." Add constraints: "Do NOT include...", "Avoid...", "Never...". Test whether constraints fix the issues.',
        successCriteria: 'Adding constraints improved previously problematic output.',
        tips: ['Common: "Don\'t use jargon", "Don\'t exceed 200 words"', 'Great for eliminating specific bad patterns', 'Combine with positive instructions for best results'],
      },
      {
        id: 'systematic-testing',
        title: 'Systematically Test Your Prompts',
        description: 'Test prompts like software: multiple inputs, edge cases, and quality criteria.',
        task: 'Pick your most important prompt. Run it 5 times with different inputs, including one edge case. Score each output on accuracy, relevance, and format. Improve the weakest area.',
        successCriteria: 'You\'ve tested systematically and improved based on scored results.',
        tips: ['Write quality criteria BEFORE testing', 'The edge case often reveals weaknesses', 'Quantifying quality makes improvement measurable'],
      },
      {
        id: 'meta-prompting',
        title: 'Use AI to Improve Your Prompts',
        description: 'The ultimate meta-skill: using AI to help you write better prompts.',
        task: 'Give AI one of your prompts and ask: "How could I improve this prompt? What information is missing? What ambiguities could cause problems?" Implement suggestions and compare.',
        successCriteria: 'AI-suggested improvements made a measurable difference in output quality.',
        tips: ['AI is surprisingly good at critiquing prompts', 'Ask for specific, actionable suggestions', 'Great habit: always ask "how could this prompt be better?"'],
      },
      {
        id: 'document-techniques',
        title: 'Build Your Advanced Techniques Cheat Sheet',
        description: 'Create a personal reference for when to use each technique.',
        task: 'Create a one-page cheat sheet with: each technique, when to use it, an example, and a common mistake to avoid. Save alongside your prompt library.',
        successCriteria: 'You have a reference covering all advanced techniques from this quest.',
        tips: ['Organize by "when to use"', 'Include your own examples', 'This is a living document — add techniques as you learn them'],
      },
    ],
  },
  {
    id: 'content-creation',
    title: 'AI-Powered Content Creation',
    description: 'Learn to use AI as a writing partner for blogs, documentation, presentations, and internal communications.',
    duration: '30-40 min',
    difficulty: 'Intermediate',
    difficultyColor: 'bg-yellow-100 text-yellow-700',
    icon: '✍️',
    xpReward: 150,
    steps: [
      {
        id: 'outline-first',
        title: 'Always Start with an Outline',
        description: 'The #1 mistake in AI content creation is asking for a finished piece upfront. Learn the outline-first approach.',
        task: 'Pick content you need to create (blog post, guide, announcement). Ask AI to generate an outline only. Review and revise before generating any content.',
        successCriteria: 'You have a solid outline that covers the right points in the right order.',
        tips: ['Outlines are cheap to revise — full drafts are expensive to revise', 'Specify audience, goal, and key points', 'Delete unnecessary sections before expanding'],
      },
      {
        id: 'section-by-section',
        title: 'Generate Content Section by Section',
        description: 'Write each section individually for better quality and control.',
        task: 'Take your outline and generate content one section at a time. Give AI the full outline for context, but ask it to write only one section. Review each before moving on.',
        successCriteria: 'You\'ve generated content section by section with consistent quality.',
        tips: ['Include the outline in each prompt for coherence', 'Adjust tone/depth per section', 'Catches problems early instead of rewriting entire drafts'],
      },
      {
        id: 'voice-and-tone',
        title: 'Match Your Brand Voice',
        description: 'Train AI to write in your specific voice and tone.',
        task: 'Find 2-3 pieces of content that represent your ideal voice. Paste them as examples and ask AI to analyze the writing style. Use that analysis as instructions for new content.',
        successCriteria: 'AI-generated content sounds like your natural writing voice.',
        tips: ['Be explicit: "conversational, uses contractions, short paragraphs"', 'Include a writing sample in every content prompt', 'AI defaults to formal — explicitly request your actual tone'],
      },
      {
        id: 'edit-and-polish',
        title: 'Use AI as an Editor',
        description: 'AI is often better as an editor than a first-draft writer.',
        task: 'Take a draft and ask AI to: (1) identify weak sections, (2) suggest stronger opening/closing, (3) cut unnecessary words, (4) improve transitions. Apply the best suggestions.',
        successCriteria: 'The edited version is noticeably stronger than the original.',
        tips: ['Specific editing requests beat "make this better"', 'Ask for tracked changes to accept/reject individually', 'Excellent at cutting fluff and tightening language'],
      },
      {
        id: 'content-workflow',
        title: 'Build Your Content Workflow',
        description: 'Combine everything into a repeatable content creation process.',
        task: 'Document your workflow: (1) brief → outline, (2) outline → sections, (3) sections → voice-matched, (4) voice-matched → edited final. Run it for one real piece of content.',
        successCriteria: 'You\'ve produced a complete piece of content using your full AI workflow.',
        tips: ['Track total time vs. your old process', 'The workflow improves with each use', 'Share with anyone who creates content'],
      },
    ],
  },
  {
    id: 'decision-framework',
    title: 'Build an AI Decision Framework',
    description: 'Use AI to make better decisions by systematically analyzing options, risks, and tradeoffs.',
    duration: '35-45 min',
    difficulty: 'Advanced',
    difficultyColor: 'bg-red-100 text-red-700',
    icon: '⚖️',
    xpReward: 200,
    steps: [
      {
        id: 'structure-decision',
        title: 'Structure Decisions for AI',
        description: 'Better than "what should I do?" — structure the decision clearly for quality analysis.',
        task: 'Think of a real work decision. Structure it as: (1) the decision to be made, (2) options available, (3) criteria that matter, (4) constraints. Present this to AI for analysis.',
        successCriteria: 'You can structure a decision in a way that gets useful AI analysis.',
        tips: ['Explicit criteria prevent AI from optimizing for the wrong thing', 'Include constraints like budget, timeline, capacity', 'List at least 3 options — AI can suggest more'],
      },
      {
        id: 'pros-cons-analysis',
        title: 'Generate Structured Pros/Cons Analysis',
        description: 'Use AI to systematically evaluate each option against your criteria.',
        task: 'Ask AI to evaluate each option against your criteria. Request: pros, cons, risks, and confidence level for each. Ask it to flag uncertainty.',
        successCriteria: 'You have a clear comparison that highlights meaningful differences between options.',
        tips: ['Table/matrix format for easy comparison', 'Request confidence ratings (high/medium/low)', 'The most valuable insight is often what AI is LEAST confident about'],
      },
      {
        id: 'red-team',
        title: 'Red-Team Your Preferred Option',
        description: 'Use AI to challenge your preferred choice — find risks and blind spots.',
        task: 'Tell AI which option you prefer and ask it to argue against it. Request: (1) strongest arguments against, (2) what could go wrong, (3) what you\'re overlooking, (4) under what conditions this option fails.',
        successCriteria: 'AI surfaced at least one risk you hadn\'t considered.',
        tips: ['Explicitly say "argue against this" — AI tends to agree otherwise', 'One of AI\'s most underrated capabilities', 'Don\'t dismiss uncomfortable challenges'],
      },
      {
        id: 'recommendation',
        title: 'Generate a Decision Recommendation',
        description: 'Synthesize analysis into a clear recommendation with rationale.',
        task: 'Create a prompt that generates a 1-page recommendation: recommended option, rationale, key risks and mitigations, first steps, and criteria for reversing the decision.',
        successCriteria: 'The recommendation is clear enough to share with your manager.',
        tips: ['"Criteria for reversal" shows you\'ve thought about failure modes', 'Keep it scannable: bold key points, use bullets', 'Explain why you DIDN\'T choose other options'],
      },
      {
        id: 'decision-template',
        title: 'Save Your Decision Framework',
        description: 'Create a reusable framework for future decisions.',
        task: 'Document: (1) structure the decision, (2) generate options, (3) evaluate against criteria, (4) red-team preferred option, (5) generate recommendation. Save all prompts.',
        successCriteria: 'You have a reusable decision framework with all prompts saved.',
        tips: ['Works for decisions big and small', 'Red-teaming is non-negotiable — always include it', 'Track decisions made with this framework and their outcomes'],
      },
    ],
  },
];
