export const REVIEW_CARDS = [
  {
    id: 'rc_001',
    type: 'multiple_choice',
    category: 'Prompt Basics',
    question: 'What makes a prompt "specific" rather than "vague"?',
    answer: 'Including context, constraints, and desired format',
    options: [
      'Using longer sentences',
      'Including context, constraints, and desired format',
      'Adding please and thank you',
      'Using technical jargon',
    ],
  },
  {
    id: 'rc_002',
    type: 'short_answer',
    category: 'Prompt Basics',
    question: 'Name the four components of the RCTF prompting framework.',
    answer: 'Role, Context, Task, and Format',
  },
  {
    id: 'rc_003',
    type: 'multiple_choice',
    category: 'Prompt Basics',
    question: 'Which RCTF component controls the length, tone, and structure of AI output?',
    answer: 'Format',
    options: ['Role', 'Context', 'Task', 'Format'],
  },
  {
    id: 'rc_004',
    type: 'multiple_choice',
    category: 'Prompt Techniques',
    question: 'What is "chain-of-thought" prompting?',
    answer: 'Asking the AI to show its reasoning step by step before giving a final answer',
    options: [
      'Sending multiple prompts in a row',
      'Asking the AI to show its reasoning step by step before giving a final answer',
      'Linking one AI tool to another',
      'Writing prompts in a specific order',
    ],
  },
  {
    id: 'rc_005',
    type: 'short_answer',
    category: 'Prompt Techniques',
    question: 'What is "few-shot" prompting and how many examples does it typically require?',
    answer: 'Providing 2-3 examples of desired input/output pairs to guide AI output. Typically 2-3 examples are sufficient.',
  },
  {
    id: 'rc_006',
    type: 'multiple_choice',
    category: 'Prompt Techniques',
    question: 'When is "negative prompting" (telling AI what NOT to do) most useful?',
    answer: 'When output is almost right but has specific recurring issues',
    options: [
      'When you have no idea what you want',
      'When output is almost right but has specific recurring issues',
      'Only when writing creative content',
      'When the AI refuses to respond',
    ],
  },
  {
    id: 'rc_007',
    type: 'multiple_choice',
    category: 'AI Safety',
    question: 'Why should you verify AI-generated statistics and data claims?',
    answer: 'AI can "hallucinate" — confidently stating incorrect facts or made-up numbers',
    options: [
      'AI always rounds numbers incorrectly',
      'AI can "hallucinate" — confidently stating incorrect facts or made-up numbers',
      'AI uses outdated databases',
      'Statistics are inherently unreliable',
    ],
  },
  {
    id: 'rc_008',
    type: 'short_answer',
    category: 'AI Safety',
    question: 'Name two types of information you should NOT paste into public AI tools.',
    answer: 'Sensitive customer data (PII) and proprietary company secrets / confidential business information',
  },
  {
    id: 'rc_009',
    type: 'multiple_choice',
    category: 'Workflows',
    question: 'What is the recommended first step when using AI to create long-form content?',
    answer: 'Generate an outline first, then expand section by section',
    options: [
      'Ask AI to write the entire piece at once',
      'Generate an outline first, then expand section by section',
      'Write it yourself and ask AI to edit',
      'Start with the conclusion',
    ],
  },
  {
    id: 'rc_010',
    type: 'short_answer',
    category: 'Workflows',
    question: 'What does "prompt chaining" mean and when should you use it?',
    answer: 'Using the output of one prompt as input for the next. Use it for multi-step tasks where each step builds on the previous one.',
  },
  {
    id: 'rc_011',
    type: 'multiple_choice',
    category: 'Prompt Basics',
    question: 'What is the "Role" component in the RCTF framework?',
    answer: 'Defining who the AI should act as, setting its expertise and perspective',
    options: [
      'The user\'s job title',
      'Defining who the AI should act as, setting its expertise and perspective',
      'The type of output format',
      'The task the AI needs to complete',
    ],
  },
  {
    id: 'rc_012',
    type: 'multiple_choice',
    category: 'Prompt Techniques',
    question: 'What is "meta-prompting"?',
    answer: 'Using AI to analyze and improve your prompts',
    options: [
      'Writing very long, detailed prompts',
      'Using multiple AI tools at once',
      'Using AI to analyze and improve your prompts',
      'Prompting about abstract concepts',
    ],
  },
  {
    id: 'rc_013',
    type: 'short_answer',
    category: 'AI Safety',
    question: 'Why is it important to have a human review AI-generated customer communications before sending?',
    answer: 'AI may produce inaccurate information, inappropriate tone, or miss important context that only a human would catch. Brand reputation and customer trust are at stake.',
  },
  {
    id: 'rc_014',
    type: 'multiple_choice',
    category: 'Workflows',
    question: 'When building an AI-powered email workflow, what should you test first?',
    answer: 'Whether the generated emails match your actual writing tone and style',
    options: [
      'How fast the AI responds',
      'Whether the generated emails match your actual writing tone and style',
      'How many emails it can generate per minute',
      'Whether it works in all email clients',
    ],
  },
  {
    id: 'rc_015',
    type: 'short_answer',
    category: 'Prompt Basics',
    question: 'Why does adding "Context" to a prompt improve AI output? Give an example.',
    answer: 'Context prevents generic responses by giving the AI specific background information. Example: "The customer is a new user who signed up yesterday" produces a more tailored response than no context.',
  },
  {
    id: 'rc_016',
    type: 'multiple_choice',
    category: 'Prompt Techniques',
    question: 'How many few-shot examples are typically needed for good results?',
    answer: '2-3 examples covering different scenarios',
    options: [
      'Just 1 example is always enough',
      '2-3 examples covering different scenarios',
      'At least 10 examples for reliability',
      'As many as possible — more is always better',
    ],
  },
  {
    id: 'rc_017',
    type: 'multiple_choice',
    category: 'AI Safety',
    question: 'What is the best approach when AI gives you an answer you are unsure about?',
    answer: 'Verify the claim against a trusted primary source before acting on it',
    options: [
      'Ask the AI if it is sure',
      'Verify the claim against a trusted primary source before acting on it',
      'Try a different AI tool for a second opinion',
      'Assume it is correct if the AI sounds confident',
    ],
  },
  {
    id: 'rc_018',
    type: 'short_answer',
    category: 'Workflows',
    question: 'What is the benefit of "red-teaming" your preferred option with AI before making a decision?',
    answer: 'It surfaces risks, blind spots, and failure modes you might not have considered, leading to more robust decisions.',
  },
  {
    id: 'rc_019',
    type: 'multiple_choice',
    category: 'Prompt Basics',
    question: 'Which of these is the BEST example of a specific Task instruction?',
    answer: '"Write a 3-paragraph product update email highlighting the new scheduling feature for existing customers"',
    options: [
      '"Write something about the product"',
      '"Write a 3-paragraph product update email highlighting the new scheduling feature for existing customers"',
      '"Write a good email"',
      '"Help me with email"',
    ],
  },
  {
    id: 'rc_020',
    type: 'short_answer',
    category: 'Workflows',
    question: 'Name two things to include when documenting an AI workflow for your team.',
    answer: 'The prompts for each step (so teammates can replicate) and estimated time savings (to motivate adoption).',
  },
];
